CREATE DATABASE Exercise1;
CREATE TABLE Exercise1.EMP_1table (EMP_NUM CHAR(3) NOT NULL, EMP_Lname VARCHAR(15) NULL, EMP_FNAME VARCHAR(15) NULL, EMP_INITIAL CHAR(1) NULL, EMP_HIREDATE DATE NULL, JOB_CODE CHAR(3) NULL, PRIMARY KEY (EMP_NUM));
INSERT INTO `Exercise1`.`EMP_1table` (`EMP_NUM`, `EMP_Lname`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`)
VALUES ('001', 'Ortega','Marina', 'V', '2023-03-28', '502');
INSERT INTO `Exercise1`.`EMP_1table` (`EMP_NUM`, `EMP_Lname`, `EMP_FNAME`, `EMP_INITIAL`, `EMP_HIREDATE`, `JOB_CODE`)
VALUES ('002', 'Doe','Jane', 'S', '2023-03-28', '503');
SELECT * FROM Exercise1.EMP_1table WHERE JOB_CODE = '502';